import Head from 'next/head';
import styles from '@/styles/home.module.css';
import Image from 'next/image';
import heroImg from '@/../public/assets/hero.png';
import { GetStaticProps } from 'next';
import { collection, getDocs } from 'firebase/firestore';
import { db } from '@/services/firebaseConnection';

interface HomeProps {
  posts: number,
  comments: number
}

export default function Home({ posts, comments }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div className={styles.logoContent}>
          <Image className={styles.hero} alt='logo tarefas' src={heroImg} priority />
        </div>
        <div className={styles.title}>
          Sistema feito para você organizar <br /> seus estudos e tarefas
        </div>

        <div className={styles.infoContent}>
          <section className={styles.box}>
            <span>+{posts} posts</span>
          </section>

          <section className={styles.box}>
            <span>+{comments} comentários</span>
          </section>
        </div>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {

  const commentRef = collection(db, "comments")
  const commentSnapshot = await getDocs(commentRef)

  const postRef = collection(db, "tarefas")
  const postSnapshot = await getDocs(postRef)

  return {
    props: {
      posts: postSnapshot.size || 0,
      comments: commentSnapshot.size || 0
    },
    revalidate: 60, //revalidada a cada 60 segundos, poupando requisições
  }
}
