import Head from 'next/head';
import styles from '@/styles/home.module.css';
import Image from 'next/image';
import heroImg from '@/../public/assets/hero.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div className={styles.logoContent}>
          <Image className={styles.hero} alt='logo tarefas' src={heroImg} priority />
        </div>
        <div className={styles.title}>
          Sistema feito para você organizar <br /> seus estudos e tarefas
        </div>

        <div className={styles.infoContent}>
          <section className={styles.box}>
            <span>+12 posts</span>
          </section>

          <section className={styles.box}>
            <span>+90 comentários</span>
          </section>
        </div>
      </main>
    </>
  )
}
